sonar.projectKey=Bank-Api
sonar.projectName=Bank-Api
sonar.projectVersion=1.0
sonar.sources=.
sonar.host.url=http://host.docker.internal:9000
sonar.login=sqp_c7bc237b89057c2f09d6ffb227670065104889fc

# sonar.tests=coverage/
# sonar.test.inclusions=**/*_test.go
# sonar.coverage.exclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage/coverage.out
sonar.exclusions = **/*_test.go,**/*.html,*.html
