CREATE TABLE IF NOT EXISTS accounts (
    id BIGSERIAL PRIMARY KEY,
    account_number VARCHAR(10) UNIQUE NOT NULL, -- ความยาว 10 หลักตาม API Spec
    owner_name VARCHAR(255) NOT NULL,
    citizen_id VARCHAR(13) UNIQUE NOT NULL,
    phone_number VARCHAR(20) NOT NULL,
    account_type VARCHAR(20) NOT NULL,          -- ALLOWED: 'SAVING', 'CURRENT'
    balance DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE', -- ALLOWED: 'ACTIVE', 'CLOSED'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);



